# Generated by Django 4.1.1 on 2022-09-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dashboardwithimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwithimage',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
