# Generated by Django 4.1.1 on 2022-09-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_dashboardwithimage_checkbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboarditem',
            name='dashboard',
        ),
        migrations.DeleteModel(
            name='DashboardWithImage',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='DashboardItem',
        ),
    ]
