# Generated by Django 4.1.1 on 2022-10-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('email_datetime_validator', models.DateTimeField(blank=True, null=True)),
                ('email_token', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('phone_confirmed', models.BooleanField(default=False)),
                ('phone_token', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_datetime_validator', models.DateTimeField(blank=True, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
