# Generated by Django 4.1.1 on 2022-10-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_confirmed_user_email_datetime_validator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
