# Generated by Django 4.1.1 on 2022-10-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_propspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propspect',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propspect',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
