# Generated by Django 4.1.1 on 2022-10-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_propspect_company_alter_propspect_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propspect',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propspect',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propspect',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propspect',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propspect',
            name='notes',
            field=models.ManyToManyField(blank=True, to='crm.notes'),
        ),
        migrations.AlterField(
            model_name='propspect',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='propspect',
            name='website',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
