# Generated by Django 4.1.1 on 2022-10-17 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_propspect_company_alter_propspect_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Propspect',
            new_name='Prospect',
        ),
    ]
