# Generated by Django 4.1.1 on 2022-10-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_rename_propspect_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crm.prospect'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='type',
            field=models.CharField(choices=[('Linkedin DM', 'Linkedin DM'), ('Email', 'Email'), ('Call', 'Call'), ('Meeting', 'Meeting'), ('Interact', 'Interact')], default='Linkedin DM', max_length=255),
        ),
    ]
