# Generated by Django 4.1.1 on 2022-10-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_tasks_prospect_alter_tasks_name_alter_tasks_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='type',
        ),
        migrations.AddField(
            model_name='tasks',
            name='notes',
            field=models.ManyToManyField(blank=True, to='crm.notes'),
        ),
    ]
