# Generated by Django 4.1.1 on 2022-10-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_tasks_type_tasks_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='emailInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('recieved_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='notes',
        ),
        migrations.AlterField(
            model_name='notes',
            name='action',
            field=models.CharField(blank=True, choices=[('Linkedin DM', 'Linkedin DM'), ('Email', 'Email'), ('Call', 'Call'), ('Meeting', 'Meeting'), ('Interact', 'Interact'), ('Other', 'Other')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.CharField(blank=True, choices=[('Linkedin DM', 'Linkedin DM'), ('Email', 'Email'), ('Call', 'Call'), ('Meeting', 'Meeting'), ('Interact', 'Interact'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
