# Generated by Django 4.1.1 on 2022-10-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_simple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariable',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariable',
            name='_product_variants',
            field=models.ManyToManyField(blank=True, to='ecommerce_simple.productsimple'),
        ),
    ]
