# Generated by Django 4.1.1 on 2022-10-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_simple', '0002_productvariable_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariable',
            name='category',
            field=models.ManyToManyField(to='ecommerce_simple.category'),
        ),
        migrations.AlterField(
            model_name='productvariable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productvariable',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productvariable',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
