# Generated by Django 4.1.1 on 2022-10-06 22:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce_simple', '0007_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='membership_user',
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
