# Generated by Django 4.1.1 on 2022-10-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_simple', '0009_remove_membership_membership_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_abstract',
            field=models.BooleanField(default=False),
        ),
    ]
