# Generated by Django 4.1.1 on 2022-10-07 04:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_simple', '0010_membership_is_abstract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address',
            new_name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='productsimple',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='productsimple',
            name='is_on_sale',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='alt_tag',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
