#on push ot pull request to main branch, run the following steps:
# - checkout the code
# - build the docker image
# - run migrate
# - deploy it to github container registry


name: Horizon Sales Ecommenrce

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/veganna/sale_dashboard:latest
        run: docker exec -it sale_dashboard python manage.py migrate
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          repository: veganna/sale_dashboard
          tags: latest
          cache-from: type=registry,ref=ghcr.io/veganna/sale_dashboard:latest



