#on push ot pull request to main branch, run the following steps:
# - checkout the code
# - build the docker image
# - run migrate
# - deploy it to github container registry


name: Horizon Sales Ecommenrce

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . -t ghcr.io/veganna/sales_dashboard:latest
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image to GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          repository: veganna/sales_dashboard
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
      - name: Run migrations
        run: docker-compose run web python manage.py migrate
      - name: deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.KEY }}
          script: |
            docker-compose pull
            docker-compose up -d
          



